security:
  providers:
    basic:
      entity:
        class: App\Entity\User
        property: email
  firewalls:
    main:
      pattern: ^/api
      guard:
        authenticators:
          - App\Infrastructure\Security\BasicAuthenticator