client_list:
    path: /client/
    controller: App\Infrastructure\Controller\Api\ClientController::index
    methods: [GET]

client_show:
    path: /client/{id}
    controller: App\Infrastructure\Controller\Api\ClientController::show
    methods: [GET]
    requirements:
        id: '\d+'
  
client_add:
    path: /client/
    controller: App\Infrastructure\Controller\Api\ClientController::add
    methods: [POST]

client_edit:
    path: /client/{id}
    controller: App\Infrastructure\Controller\Api\ClientController::edit
    methods: [PUT, PATCH]
    requirements:
        id: '\d+'

client_delete:
    path: /client/{id}
    controller: App\Infrastructure\Controller\Api\ClientController::delete
    methods: [DELETE]
    requirements:
        id: '\d+'

client_search:
    path: /client/{field}/{value}
    controller: App\Infrastructure\Controller\Api\ClientController::find
    methods: [GET]
    requirements:
        field: '[a-zA-Z]+'